from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from proyecta360.main import app  # noqa: E402

CONTRACTS_DIR = ROOT / "contracts" / "api"
OPENAPI_PATH = CONTRACTS_DIR / "openapi.json"
TYPES_PATH = CONTRACTS_DIR / "types.ts"
ENDPOINTS_PATH = CONTRACTS_DIR / "endpoints.ts"


def pascal_case(value: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", value)
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


def operation_name(method: str, path: str) -> str:
    cleaned = path.strip("/").replace("api/", "")
    cleaned = re.sub(r"{([^}]+)}", r"by-\1", cleaned)
    return pascal_case(f"{method.lower()}-{cleaned}") or pascal_case(method)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def ts_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "anyOf" in schema:
        return " | ".join(sorted({ts_type(item) for item in schema["anyOf"]}))
    if "oneOf" in schema:
        return " | ".join(sorted({ts_type(item) for item in schema["oneOf"]}))
    if "allOf" in schema:
        return " & ".join(ts_type(item) for item in schema["allOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        if schema.get("format") == "binary":
            return "File"
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"{ts_type(schema.get('items'))}[]"
    if kind == "object":
        if "additionalProperties" in schema:
            return f"Record<string, {ts_type(schema.get('additionalProperties'))}>"
        return inline_object(schema)
    return "unknown"


def inline_object(schema: dict[str, Any]) -> str:
    properties = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    if not properties:
        return "Record<string, unknown>"
    fields = []
    for name, field_schema in sorted(properties.items()):
        optional = "" if name in required else "?"
        fields.append(f"  {json.dumps(name)}{optional}: {ts_type(field_schema)};")
    return "{\n" + "\n".join(fields) + "\n}"


def schema_interface(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" or "properties" in schema:
        body = inline_object(schema)
        return f"export interface {name} {body}\n"
    return f"export type {name} = {ts_type(schema)};\n"


def response_type(operation: dict[str, Any]) -> str:
    response = (operation.get("responses") or {}).get("200") or {}
    content = response.get("content") or {}
    schema = (content.get("application/json") or {}).get("schema")
    return ts_type(schema)


def request_body_type(operation: dict[str, Any]) -> str:
    body = operation.get("requestBody") or {}
    content = body.get("content") or {}
    schema = (content.get("application/json") or {}).get("schema")
    if schema:
        return ts_type(schema)
    if "multipart/form-data" in content:
        return "FormData"
    return "undefined"


def generate_types(openapi: dict[str, Any]) -> str:
    schemas = (openapi.get("components") or {}).get("schemas") or {}
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_api_contracts.py. Do not edit by hand.",
        "",
    ]
    for name, schema in sorted(schemas.items()):
        lines.append(schema_interface(name, schema))

    lines.append("export interface ApiOperationMap {")
    for path, methods in sorted((openapi.get("paths") or {}).items()):
        for method, operation in sorted(methods.items()):
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            name = operation.get("operationId") or operation_name(method, path)
            lines.append(f"  {json.dumps(name)}: {{")
            lines.append(f"    method: {json.dumps(method.upper())};")
            lines.append(f"    path: {json.dumps(path)};")
            lines.append(f"    request: {request_body_type(operation)};")
            lines.append(f"    response: {response_type(operation)};")
            lines.append("  };")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_endpoints(openapi: dict[str, Any]) -> str:
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_api_contracts.py. Do not edit by hand.",
        "",
        "export const API_ENDPOINTS = {",
    ]
    for path, methods in sorted((openapi.get("paths") or {}).items()):
        for method, operation in sorted(methods.items()):
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            name = operation.get("operationId") or operation_name(method, path)
            lines.append(f"  {name}: {{ method: {json.dumps(method.upper())}, path: {json.dumps(path)} }},")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    CONTRACTS_DIR.mkdir(parents=True, exist_ok=True)
    openapi = app.openapi()
    OPENAPI_PATH.write_text(json.dumps(openapi, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    TYPES_PATH.write_text(generate_types(openapi), encoding="utf-8")
    ENDPOINTS_PATH.write_text(generate_endpoints(openapi), encoding="utf-8")
    print(f"Wrote {OPENAPI_PATH.relative_to(ROOT)}")
    print(f"Wrote {TYPES_PATH.relative_to(ROOT)}")
    print(f"Wrote {ENDPOINTS_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
