/* eslint-disable */
// Generated by scripts/generate_api_contracts.py. Do not edit by hand.

export interface AgileCycleIn {
  "capacity"?: number;
  "close_summary"?: string;
  "cycle_type"?: string;
  "end_date": string;
  "goal"?: string;
  "name": string;
  "project_id": number;
  "start_date": string;
  "status"?: string;
  "velocity"?: number;
}

export interface AiAnalysisIn {
  "include_budget"?: boolean;
  "include_conversations"?: boolean;
  "include_deliverables"?: boolean;
  "include_evidences"?: boolean;
  "include_history"?: boolean;
  "include_resources"?: boolean;
  "include_risks"?: boolean;
  "include_schedule"?: boolean;
}

export interface AiChatIn {
  "author"?: string;
  "project_id": number;
  "question": string;
}

export interface AiPlanIn {
  "create_records"?: boolean;
  "execution_methodology"?: string;
  "horizon_weeks"?: number;
  "objective": string;
  "project_id": number;
}

export interface AiProjectChatIn {
  "message": string;
  "mode"?: string;
}

export interface AiRecommendationUpdate {
  "description"?: null | string;
  "edited_payload"?: Record<string, unknown> | null;
  "expected_impact"?: null | string;
  "justification"?: null | string;
  "priority"?: null | string;
  "proposed_payload"?: Record<string, unknown> | null;
  "title"?: null | string;
}

export interface AiReportIn {
  "audience"?: string;
  "project_id": number;
}

export interface AiSettingsIn {
  "api_key"?: string;
  "config"?: Record<string, unknown>;
  "model"?: string;
  "provider"?: string;
}

export interface Body_import_project_csv_api_projects_import_csv_post {
  "file": File;
}

export interface Body_upload_evidence_api_evidences_upload_post {
  "description"?: string;
  "entity_id"?: null | number;
  "entity_type"?: string;
  "file": File;
  "project_id": number;
  "uploaded_by"?: string;
}

export interface BudgetEntryIn {
  "category"?: string;
  "executed_amount"?: number;
  "month": string;
  "notes"?: string;
  "planned_amount"?: number;
  "project_id": number;
}

export interface ComponentIn {
  "methodology"?: string;
  "name": string;
  "objective"?: string;
  "owner"?: string;
  "progress"?: number;
  "project_id": number;
}

export interface ConversationMessageIn {
  "author"?: string;
  "evidence_url"?: string;
  "mentions"?: string;
  "message": string;
  "message_type"?: string;
  "project_id": number;
  "thread_id": number;
}

export interface ConversationThreadIn {
  "category"?: string;
  "context_id"?: null | number;
  "context_type"?: string;
  "created_by"?: string;
  "project_id": number;
  "status"?: string;
  "title": string;
}

export interface DeliverableIn {
  "component_id"?: null | number;
  "deliverable_type"?: string;
  "description"?: string;
  "due_date"?: null | string;
  "evidence_url"?: string;
  "name": string;
  "owner"?: string;
  "project_id": number;
  "status"?: string;
}

export interface DependencyIn {
  "dependency_type"?: string;
  "lag_days"?: number;
  "predecessor_id": number;
  "project_id": number;
  "successor_id": number;
}

export interface HTTPValidationError {
  "detail"?: ValidationError[];
}

export interface ProjectIn {
  "assumptions"?: string;
  "budget"?: number;
  "consequence_if_not_done"?: string;
  "constraints"?: string;
  "contractual_end_date"?: null | string;
  "cultural_context"?: string;
  "currency"?: string;
  "current_situation"?: string;
  "description"?: string;
  "external_dependencies"?: string;
  "general_objective"?: string;
  "geographic_context"?: string;
  "institutional_context"?: string;
  "methodology"?: string;
  "name": string;
  "objective_indicators"?: string;
  "parameters"?: Record<string, unknown>;
  "political_context"?: string;
  "priority"?: string;
  "problem_statement"?: string;
  "project_code"?: string;
  "project_context"?: string;
  "project_manager": string;
  "project_type"?: string;
  "regulatory_constraints"?: string;
  "requesting_area"?: string;
  "responsible_team"?: string;
  "scope_excluded"?: string;
  "scope_included"?: string;
  "socioeconomic_context"?: string;
  "specific_objectives"?: string;
  "sponsor": string;
  "stakeholders"?: string;
  "stakeholders_context"?: string;
  "start_date": string;
  "status"?: string;
  "success_criteria"?: string;
}

export interface ProjectUpdate {
  "assumptions"?: null | string;
  "budget"?: null | number;
  "consequence_if_not_done"?: null | string;
  "constraints"?: null | string;
  "contractual_end_date"?: null | string;
  "cultural_context"?: null | string;
  "currency"?: null | string;
  "current_situation"?: null | string;
  "description"?: null | string;
  "external_dependencies"?: null | string;
  "general_objective"?: null | string;
  "geographic_context"?: null | string;
  "institutional_context"?: null | string;
  "methodology"?: null | string;
  "name"?: null | string;
  "objective_indicators"?: null | string;
  "parameters"?: Record<string, unknown> | null;
  "political_context"?: null | string;
  "priority"?: null | string;
  "problem_statement"?: null | string;
  "project_code"?: null | string;
  "project_context"?: null | string;
  "project_manager"?: null | string;
  "project_type"?: null | string;
  "regulatory_constraints"?: null | string;
  "requesting_area"?: null | string;
  "responsible_team"?: null | string;
  "scope_excluded"?: null | string;
  "scope_included"?: null | string;
  "socioeconomic_context"?: null | string;
  "specific_objectives"?: null | string;
  "sponsor"?: null | string;
  "stakeholders"?: null | string;
  "stakeholders_context"?: null | string;
  "start_date"?: null | string;
  "status"?: null | string;
  "success_criteria"?: null | string;
}

export interface ResourceIn {
  "capacity"?: number;
  "email"?: string;
  "name": string;
  "project_id": number;
  "role"?: string;
}

export interface RiskIn {
  "actual_impact"?: string;
  "contingency_plan"?: string;
  "impact"?: number;
  "materialized_date"?: null | string;
  "mitigation_plan"?: string;
  "observations"?: string;
  "owner"?: string;
  "probability"?: number;
  "project_id": number;
  "response"?: string;
  "status"?: string;
  "title": string;
}

export interface SprintIn {
  "capacity"?: number;
  "close_summary"?: string;
  "cycle_type"?: string;
  "end_date": string;
  "goal"?: string;
  "name": string;
  "project_id": number;
  "start_date": string;
  "status"?: string;
  "velocity"?: number;
}

export interface StoryIn {
  "assignee"?: string;
  "blocked_reason"?: string;
  "board_order"?: number;
  "completed_at"?: string;
  "component_id"?: null | number;
  "deliverable_id"?: null | number;
  "description"?: string;
  "labels"?: string[];
  "master_task_id"?: null | number;
  "points"?: number;
  "priority"?: string;
  "project_id": number;
  "sprint_id"?: null | number;
  "started_at"?: string;
  "status"?: string;
  "title": string;
  "work_type"?: string;
}

export interface TaskIn {
  "budget"?: number;
  "component_id"?: null | number;
  "dependency_type"?: string;
  "description"?: string;
  "duration_days"?: number;
  "end_date"?: null | string;
  "is_expanded"?: number;
  "lag_days"?: number;
  "order_index"?: number;
  "outline_level"?: number;
  "owner"?: string;
  "parent_id"?: null | number;
  "phase"?: string;
  "predecessor_id"?: null | number;
  "progress"?: number;
  "project_id": number;
  "start_date"?: null | string;
  "status"?: string;
  "story_points"?: number;
  "task_type"?: string;
  "title": string;
}

export interface TaskUpdate {
  "budget"?: null | number;
  "component_id"?: null | number;
  "description"?: null | string;
  "duration_days"?: null | number;
  "end_date"?: null | string;
  "is_expanded"?: null | number;
  "order_index"?: null | number;
  "outline_level"?: null | number;
  "owner"?: null | string;
  "parent_id"?: null | number;
  "phase"?: null | string;
  "progress"?: null | number;
  "start_date"?: null | string;
  "status"?: null | string;
  "story_points"?: null | number;
  "task_type"?: null | string;
  "title"?: null | string;
}

export interface ValidationError {
  "loc": number | string[];
  "msg": string;
  "type": string;
}

export interface WorkItemIn {
  "assignee"?: string;
  "blocked_reason"?: string;
  "board_order"?: number;
  "completed_at"?: string;
  "component_id"?: null | number;
  "deliverable_id"?: null | number;
  "description"?: string;
  "labels"?: string[];
  "master_task_id"?: null | number;
  "points"?: number;
  "priority"?: string;
  "project_id": number;
  "sprint_id"?: null | number;
  "started_at"?: string;
  "status"?: string;
  "title": string;
  "work_type"?: string;
}

export interface ApiOperationMap {
  "index__get": {
    method: "GET";
    path: "/";
    request: undefined;
    response: unknown;
  };
  "create_agile_cycle_api_agile_cycles_post": {
    method: "POST";
    path: "/api/agile-cycles";
    request: AgileCycleIn;
    response: Record<string, unknown>;
  };
  "get_analysis_run_api_ai_analysis_runs__run_id__get": {
    method: "GET";
    path: "/api/ai/analysis-runs/{run_id}";
    request: undefined;
    response: Record<string, unknown>;
  };
  "ai_chat_api_ai_chat_post": {
    method: "POST";
    path: "/api/ai/chat";
    request: AiChatIn;
    response: Record<string, unknown>;
  };
  "ai_generate_plan_api_ai_generate_plan_post": {
    method: "POST";
    path: "/api/ai/generate-plan";
    request: AiPlanIn;
    response: Record<string, unknown>;
  };
  "get_recommendation_api_ai_recommendations__recommendation_id__get": {
    method: "GET";
    path: "/api/ai/recommendations/{recommendation_id}";
    request: undefined;
    response: Record<string, unknown>;
  };
  "update_recommendation_api_ai_recommendations__recommendation_id__patch": {
    method: "PATCH";
    path: "/api/ai/recommendations/{recommendation_id}";
    request: AiRecommendationUpdate;
    response: Record<string, unknown>;
  };
  "apply_recommendation_api_ai_recommendations__recommendation_id__apply_post": {
    method: "POST";
    path: "/api/ai/recommendations/{recommendation_id}/apply";
    request: undefined;
    response: Record<string, unknown>;
  };
  "approve_recommendation_api_ai_recommendations__recommendation_id__approve_post": {
    method: "POST";
    path: "/api/ai/recommendations/{recommendation_id}/approve";
    request: undefined;
    response: Record<string, unknown>;
  };
  "recommendation_history_api_ai_recommendations__recommendation_id__history_get": {
    method: "GET";
    path: "/api/ai/recommendations/{recommendation_id}/history";
    request: undefined;
    response: Record<string, unknown>;
  };
  "reject_recommendation_api_ai_recommendations__recommendation_id__reject_post": {
    method: "POST";
    path: "/api/ai/recommendations/{recommendation_id}/reject";
    request: undefined;
    response: Record<string, unknown>;
  };
  "undo_recommendation_api_ai_recommendations__recommendation_id__undo_post": {
    method: "POST";
    path: "/api/ai/recommendations/{recommendation_id}/undo";
    request: undefined;
    response: Record<string, unknown>;
  };
  "ai_report_api_ai_report_post": {
    method: "POST";
    path: "/api/ai/report";
    request: AiReportIn;
    response: Record<string, unknown>;
  };
  "clear_ai_settings_api_ai_settings_delete": {
    method: "DELETE";
    path: "/api/ai/settings";
    request: undefined;
    response: Record<string, string>;
  };
  "get_ai_settings_api_ai_settings_get": {
    method: "GET";
    path: "/api/ai/settings";
    request: undefined;
    response: Record<string, unknown>;
  };
  "save_ai_settings_api_ai_settings_post": {
    method: "POST";
    path: "/api/ai/settings";
    request: AiSettingsIn;
    response: Record<string, unknown>;
  };
  "test_ai_connection_api_ai_test_connection_post": {
    method: "POST";
    path: "/api/ai/test-connection";
    request: undefined;
    response: Record<string, unknown>;
  };
  "login_api_auth_login_post": {
    method: "POST";
    path: "/api/auth/login";
    request: undefined;
    response: Record<string, unknown>;
  };
  "logout_api_auth_logout_post": {
    method: "POST";
    path: "/api/auth/logout";
    request: undefined;
    response: Record<string, string>;
  };
  "me_api_auth_me_get": {
    method: "GET";
    path: "/api/auth/me";
    request: undefined;
    response: Record<string, unknown>;
  };
  "bootstrap_api_bootstrap_get": {
    method: "GET";
    path: "/api/bootstrap";
    request: undefined;
    response: Record<string, unknown>;
  };
  "create_budget_entry_api_budget_entries_post": {
    method: "POST";
    path: "/api/budget-entries";
    request: BudgetEntryIn;
    response: Record<string, unknown>;
  };
  "delete_budget_entry_api_budget_entries__entry_id__delete": {
    method: "DELETE";
    path: "/api/budget-entries/{entry_id}";
    request: undefined;
    response: Record<string, string>;
  };
  "create_component_api_components_post": {
    method: "POST";
    path: "/api/components";
    request: ComponentIn;
    response: Record<string, unknown>;
  };
  "create_conversation_api_conversations_post": {
    method: "POST";
    path: "/api/conversations";
    request: ConversationThreadIn;
    response: Record<string, unknown>;
  };
  "create_conversation_message_api_conversations__thread_id__messages_post": {
    method: "POST";
    path: "/api/conversations/{thread_id}/messages";
    request: ConversationMessageIn;
    response: Record<string, unknown>;
  };
  "create_deliverable_api_deliverables_post": {
    method: "POST";
    path: "/api/deliverables";
    request: DeliverableIn;
    response: Record<string, unknown>;
  };
  "create_dependency_api_dependencies_post": {
    method: "POST";
    path: "/api/dependencies";
    request: DependencyIn;
    response: Record<string, unknown>;
  };
  "delete_dependency_api_dependencies__dependency_id__delete": {
    method: "DELETE";
    path: "/api/dependencies/{dependency_id}";
    request: undefined;
    response: Record<string, string>;
  };
  "upload_evidence_api_evidences_upload_post": {
    method: "POST";
    path: "/api/evidences/upload";
    request: FormData;
    response: Record<string, unknown>;
  };
  "download_evidence_api_evidences__evidence_id__download_get": {
    method: "GET";
    path: "/api/evidences/{evidence_id}/download";
    request: undefined;
    response: unknown;
  };
  "health_api_health_get": {
    method: "GET";
    path: "/api/health";
    request: undefined;
    response: Record<string, unknown>;
  };
  "ready_api_health_ready_get": {
    method: "GET";
    path: "/api/health/ready";
    request: undefined;
    response: Record<string, unknown>;
  };
  "catalog_api_i18n_catalog__locale__get": {
    method: "GET";
    path: "/api/i18n/catalog/{locale}";
    request: undefined;
    response: Record<string, unknown>;
  };
  "languages_api_i18n_languages_get": {
    method: "GET";
    path: "/api/i18n/languages";
    request: undefined;
    response: Record<string, unknown>;
  };
  "operational_metrics_api_ops_metrics_get": {
    method: "GET";
    path: "/api/ops/metrics";
    request: undefined;
    response: Record<string, unknown>;
  };
  "get_portfolio_api_portfolio_get": {
    method: "GET";
    path: "/api/portfolio";
    request: undefined;
    response: Record<string, unknown>;
  };
  "create_project_api_projects_post": {
    method: "POST";
    path: "/api/projects";
    request: ProjectIn;
    response: Record<string, unknown>;
  };
  "import_project_csv_api_projects_import_csv_post": {
    method: "POST";
    path: "/api/projects/import/csv";
    request: FormData;
    response: Record<string, unknown>;
  };
  "delete_project_api_projects__project_id__delete": {
    method: "DELETE";
    path: "/api/projects/{project_id}";
    request: undefined;
    response: Record<string, unknown>;
  };
  "update_project_api_projects__project_id__put": {
    method: "PUT";
    path: "/api/projects/{project_id}";
    request: ProjectUpdate;
    response: Record<string, unknown>;
  };
  "list_analysis_runs_api_projects__project_id__ai_analysis_runs_get": {
    method: "GET";
    path: "/api/projects/{project_id}/ai/analysis-runs";
    request: undefined;
    response: Record<string, unknown>;
  };
  "analyze_project_api_projects__project_id__ai_analyze_post": {
    method: "POST";
    path: "/api/projects/{project_id}/ai/analyze";
    request: AiAnalysisIn;
    response: Record<string, unknown>;
  };
  "project_ai_chat_api_projects__project_id__ai_chat_post": {
    method: "POST";
    path: "/api/projects/{project_id}/ai/chat";
    request: AiProjectChatIn;
    response: Record<string, unknown>;
  };
  "ai_history_api_projects__project_id__ai_history_get": {
    method: "GET";
    path: "/api/projects/{project_id}/ai/history";
    request: undefined;
    response: Record<string, unknown>;
  };
  "list_recommendations_api_projects__project_id__ai_recommendations_get": {
    method: "GET";
    path: "/api/projects/{project_id}/ai/recommendations";
    request: undefined;
    response: Record<string, unknown>;
  };
  "export_project_csv_api_projects__project_id__export_csv_get": {
    method: "GET";
    path: "/api/projects/{project_id}/export/csv";
    request: undefined;
    response: unknown;
  };
  "export_project_html_api_projects__project_id__export_html_get": {
    method: "GET";
    path: "/api/projects/{project_id}/export/html";
    request: undefined;
    response: unknown;
  };
  "export_project_json_api_projects__project_id__export_json_get": {
    method: "GET";
    path: "/api/projects/{project_id}/export/json";
    request: undefined;
    response: unknown;
  };
  "intelligence_api_projects__project_id__intelligence_get": {
    method: "GET";
    path: "/api/projects/{project_id}/intelligence";
    request: undefined;
    response: Record<string, unknown>;
  };
  "metrics_api_projects__project_id__metrics_get": {
    method: "GET";
    path: "/api/projects/{project_id}/metrics";
    request: undefined;
    response: Record<string, unknown>;
  };
  "export_project_report_pdf_api_projects__project_id__report_pdf_get": {
    method: "GET";
    path: "/api/projects/{project_id}/report/pdf";
    request: undefined;
    response: unknown;
  };
  "linkable_tasks_api_projects__project_id__scrum_linkable_tasks_get": {
    method: "GET";
    path: "/api/projects/{project_id}/scrum/linkable-tasks";
    request: undefined;
    response: Record<string, unknown>;
  };
  "task_scrum_summary_api_projects__project_id__tasks__task_id__scrum_summary_get": {
    method: "GET";
    path: "/api/projects/{project_id}/tasks/{task_id}/scrum-summary";
    request: undefined;
    response: Record<string, unknown>;
  };
  "create_resource_api_resources_post": {
    method: "POST";
    path: "/api/resources";
    request: ResourceIn;
    response: Record<string, unknown>;
  };
  "create_risk_api_risks_post": {
    method: "POST";
    path: "/api/risks";
    request: RiskIn;
    response: Record<string, unknown>;
  };
  "seed_api_seed_post": {
    method: "POST";
    path: "/api/seed";
    request: undefined;
    response: Record<string, string>;
  };
  "create_sprint_api_sprints_post": {
    method: "POST";
    path: "/api/sprints";
    request: SprintIn;
    response: Record<string, unknown>;
  };
  "create_story_api_stories_post": {
    method: "POST";
    path: "/api/stories";
    request: StoryIn;
    response: Record<string, unknown>;
  };
  "update_story_api_stories__story_id__put": {
    method: "PUT";
    path: "/api/stories/{story_id}";
    request: StoryIn;
    response: Record<string, unknown>;
  };
  "create_task_api_tasks_post": {
    method: "POST";
    path: "/api/tasks";
    request: TaskIn;
    response: Record<string, unknown>;
  };
  "delete_task_api_tasks__task_id__delete": {
    method: "DELETE";
    path: "/api/tasks/{task_id}";
    request: undefined;
    response: Record<string, string>;
  };
  "update_task_api_tasks__task_id__put": {
    method: "PUT";
    path: "/api/tasks/{task_id}";
    request: TaskUpdate;
    response: Record<string, unknown>;
  };
  "indent_task_api_tasks__task_id__indent_post": {
    method: "POST";
    path: "/api/tasks/{task_id}/indent";
    request: undefined;
    response: Record<string, unknown>;
  };
  "outdent_task_api_tasks__task_id__outdent_post": {
    method: "POST";
    path: "/api/tasks/{task_id}/outdent";
    request: undefined;
    response: Record<string, unknown>;
  };
  "toggle_task_api_tasks__task_id__toggle_post": {
    method: "POST";
    path: "/api/tasks/{task_id}/toggle";
    request: undefined;
    response: Record<string, unknown>;
  };
  "create_work_item_api_work_items_post": {
    method: "POST";
    path: "/api/work-items";
    request: WorkItemIn;
    response: Record<string, unknown>;
  };
  "update_work_item_api_work_items__item_id__put": {
    method: "PUT";
    path: "/api/work-items/{item_id}";
    request: WorkItemIn;
    response: Record<string, unknown>;
  };
  "favicon_favicon_ico_get": {
    method: "GET";
    path: "/favicon.ico";
    request: undefined;
    response: unknown;
  };
}
